// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Url         sql.NullString
	StartingAt  sql.NullTime
	EndingAt    sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	GmID        uuid.NullUUID
}

type User struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UserCredential struct {
	ID           uuid.UUID
	PasswordHash string
	Email        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
